Cleaned up stack traces
Now

  Exception: nil does not respond to 'setStructure'
  ---------
  nil setStructure                     ParagraphRecognizer.io 9
  ParagraphRecognizer extractStructure Recognizer.io 4
  Recognizer examineLines              mark.io 8

Instead of

  Exception: nil does not respond to 'setStructure'
  ---------
  Coroutine pauseCurrentAndResumeSelf A4_Exception.io 150
  Coroutine resumeParentCoroutine     A4_Exception.io 161
  Coroutine raiseException            A4_Exception.io 243
  nil setStructure                    ParagraphRecognizer.io 9
  Exception raise                     Z_Importer.io 55
  Importer import                     Z_Importer.io 60
  ParagraphRecognizer extractStructureRecognizer.io 4
  Recognizer examineLines             mark.io 8